export type Spectrum={left:string;right:string};export type Pack={id:string;name:string;emoji:string;spectra:Spectrum[]};
const p=(x:string)=>x.split("~").map(v=>{const[a,b]=v.split("|");return{left:a,right:b}});
export const PACKS:Pack[]=[
 {id:"daily",name:"Daily Signals",emoji:"☀️",spectra:p("Wake early|Sleep in~Homemade|Takeout~Text it|Call it~Spontaneous|Planned~Window seat|Aisle seat~Hot coffee|Iced coffee~City walk|Nature walk~Early|Fashionably late~Notebook|Notes app~Sweet snack|Salty snack~Library|Bookstore~Morning shower|Night shower~One trip|Many trips~Rewatch|Try new~Shoes on|Shoes off~Calendar full|Calendar open~Phone camera|Film camera~Dine in|Picnic~Long playlist|One album~Talk it out|Think it through~Minimalist|Maximalist~Big group|One-on-one~Buy it|Borrow it~Sunrise|Sunset~Workout solo|Workout class~House party|Going out~Fast reply|Thoughtful reply~Clean now|Clean later~Early bird|Night owl~Routine|Surprise" )},
 {id:"culture",name:"Culture Club",emoji:"🎬",spectra:p("Cult classic|Blockbuster~Book first|Screen first~Serious|Silly~Comfort watch|Challenge watch~Live music|Studio recording~Plot|Character~Museum|Concert~Subtitles on|Subtitles off~Slow burn|Instant hook~Classic|Contemporary~Indie|Mainstream~Reboot|Original~Solo artist|Ensemble~Jukebox|Algorithm~Theater|Couch~Fiction|Documentary~Binge|Weekly~Lyrics|Melody~Trailer avoider|Trailer watcher~Film camera|Digital polish~Hero|Antihero~Happy ending|Ambiguous ending~Poetry|Prose~Broadway|Basement show~Vintage|Futuristic~Spooky|Cozy~Meme|Quote~Cover|Original~Drama|Comedy~Art house|Popcorn" )},
 {id:"food",name:"Taste Test",emoji:"🍋",spectra:p("Mild|Extra spicy~Crunchy|Chewy~Brunch|Midnight snack~Sauce aside|Sauce everywhere~Sweet breakfast|Savory breakfast~Shared plates|Own entrée~Tiny bites|Giant bowl~Familiar order|New item~Lemon|Chocolate~Street food|Tasting menu~Breakfast dinner|Dinner breakfast~Fork|Hands~Fancy plating|Big portions~Sparkling|Still~Crispy edge|Soft center~Dessert first|Dessert last~Dip|Drizzle~Pickles|No pickles~Coffee shop|Bakery~Noodles|Rice~Salad|Sandwich~Fruit dessert|Baked dessert~Food truck|Sit-down~Spice blend|Fresh herbs~Comfort food|Health kick~Pie|Cake~Local spot|Chain favorite~Snack board|Full meal~Sour|Sweet~Recipe follower|Improviser" )},
 {id:"places",name:"Places, Please",emoji:"🗺️",spectra:p("Mountains|Beach~Small town|Big city~Museum day|Theme park~Train ride|Road trip~Camping|Hotel~Map out|Wander~Landmark|Hidden gem~Coast|Countryside~Cabin|Apartment~Passport|Staycation~Busy market|Quiet café~Sun|Snow~Day trip|Long haul~Window view|Front row~North|South~Trail|Boardwalk~Hostel|Resort~Early flight|Red-eye~Desert|Forest~Old world|New world~Tour guide|Self guided~National park|City park~Souvenir|Photo~Ferry|Subway~Tent|Glamping~Rainy day|Clear sky~Neighborhood bar|Rooftop bar~Familiar route|Scenic route~Museum map|No plan~Beach read|Hiking snack" )},
 {id:"people",name:"Human Energy",emoji:"✨",spectra:p("Quiet confidence|Big energy~Diplomatic|Direct~Listener|Storyteller~Optimist|Realist~Competitive|Collaborative~Reserved|Open book~Go with flow|Take charge~Punctual|Flexible~Heart|Head~Tease|Encourage~Host|Guest~Group chat|Private text~Risk taker|Careful planner~Tradition|Reinvention~Quick decision|Deep thought~People watcher|Starter~Practical gift|Sentimental gift~Straight face|Expressive face~Forgive fast|Remember all~Calm|Chaotic good~Coach|Cheerleader~Homebody|Social butterfly~Bold|Understated~Debate|Agree~Routine|Variety~Honest|Tactful~Independent|Team player~Nostalgic|Forward-looking~One best friend|Many friends~Spark|Stability" )},
 {id:"internet",name:"Internet Brain",emoji:"💻",spectra:p("Voice note|Typing~Bookmark|Screenshot~Group chat|Server~Desktop|Mobile~Dark mode|Light mode~Search it|Ask friend~GIF|Emoji~Podcast|Short video~Playlist|Radio~Pinned tab|Clean tabs~Mute|Unfollow~Link drop|Long explanation~Shortcut|Menu click~Email|DM~Wi-Fi|Data~Autoplay|Manual~Online shop|In-store~Infinite scroll|One article~Tab hoarder|Tab closer~Password manager|Memory~Profile pic|No avatar~Comment|Lurk~Video call|Phone call~Cloud|Hard drive~Wallpaper|Plain~QR code|Typed URL~Notifications on|Off~Laptop|Tablet~E-reader|Paper~Rabbit hole|Focus mode" )},
 {id:"throwback",name:"Throwback Frequency",emoji:"📼",spectra:p("Saturday cartoons|Errands~CD binder|Streaming queue~Arcade|Console~School dance|House party~Landline|Cell phone~Mixtape|Playlist~Mall|Main street~Stickers|Digital badges~Summer camp|Summer job~Yearbook|Photo dump~Disposable camera|Selfie~Video store|Streaming app~Roller rink|Bowling~Cartoon theme|Pop intro~Handwritten note|Voice memo~Sleepover|Group vacation~Local radio|Algorithm~Board game|Video game~Photo album|Camera roll~Backyard|Bedroom~Pizza party|Cookout~Comic book|Webtoon~Flip phone|Smart watch~After school|Midnight~Trick-or-treat|Costume party~Weekend chores|Weekend plans" )},
 {id:"wild",name:"Wild Cards",emoji:"🪐",spectra:p("Useful power|Fun power~Dragon|Giant robot~Past travel|Future travel~Teleport|Fly~Mermaid|Astronaut~Secret lair|Treehouse~Alien friend|Ghost friend~Magic wand|Magic book~Talking animal|Tiny dinosaur~Strength|Speed~Underwater city|Sky city~Moon base|Jungle temple~Invisible|Mind reading~Treasure map|Mystery door~Cursed item|Lucky charm~Storm chaser|Deep diver~Space opera|Fairy tale~Portal|Puzzle box~Robot butler|Dragon chauffeur~Giant library|Giant kitchen~Winter forever|Summer forever~Perfect day|Surprise adventure~Glowing forest|Crystal cave~Wizard duel|Dance battle~Friendly monster|Mischief fairy~Ancient ruins|Future ruins~Cloud castle|Underground city~Magic mirror|Magic compass~Wish careful|Wish bold" )},
 {id:"work",name:"Work & Play",emoji:"🎯",spectra:p("Deep focus|Quick wins~Brainstorm|Execute~List|Wing it~Big picture|Detail~Office|Café~Early start|Late sprint~One task|Multitask~Sketch|Build~Feedback now|Later~Solo|Co-create~Presentation|Spreadsheet~Sticky notes|Whiteboard~Deadline|Inspiration~Promotion|Freedom~Work hard|Work smart~Inbox zero|Search later~Shortcut|Best practice~Prototype|Polish~Practice|Improvise~Expertise|Curiosity~Ambition|Balance~Mentor|Peer~Remote|In person~Meeting|Async~Perfect|Shipped~Planner|Adapter~Calendar block|To-do list~Sprint|Marathon~Idea|Execution" )},
 {id:"afterdark",name:"After Dark",emoji:"🌙",spectra:p("Dance floor|Corner booth~Late dinner|Early dessert~Rooftop|Basement~Mocktail|Cocktail~Live DJ|Live band~Dress up|Comfortable~Stay out|Head home~Night drive|Night walk~Neon|Candlelight~Secrets|Stories~First date|Long-time love~Laugh loud|Speak low~Big gesture|Small detail~Busy bar|Quiet lounge~Spontaneous|Reserved~Dessert bar|Coffee shop~Movie night|Game night~City lights|Star lights~Last call|First train~Deep talk|Dumb jokes~Crowded room|Empty room~Mystery|Romance~Slow song|Fast song~Polaroid|Memory~Flirt|Tease~Fancy|Casual~Surprise|Routine~Midnight snack|Sunrise breakfast~Keep going|Leave wanting~New connection|Familiar comfort" )}
];
