"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { PACKS, type Pack, type Spectrum } from "@/lib/packs";
import { MultiplayerLobby } from "@/components/multiplayer-lobby";
import type { RoomSnapshot } from "@/lib/game-library";
import { createWavelengthPreviewPublisher, getCurrentRoomPlayer, getCurrentWavelengthRound, listRoomPlayers, subscribeToRoom, subscribeToRoomPlayers, subscribeToWavelengthPreviews, wavelengthRevealRound, wavelengthStartGame, wavelengthStartRound, wavelengthSubmitClue, wavelengthSubmitTune, wavelengthTimeoutPhase, type CurrentRoomPlayer, type RoomPlayer, type WavelengthPreview } from "@/lib/game-room";
import { Countdown } from "@/components/countdown";

type Phase = "library" | "game" | "clue" | "tune" | "reveal_pending" | "reveal" | "timeout" | "complete";
type DialMarker = { id: string; label: string; value: number };
const clamp = (value: number) => Math.max(0, Math.min(100, value));
const randomTarget = () => 12 + Math.floor(Math.random() * 77);
const scoreGuess = (needle: number, target: number) => { const distance = Math.abs(needle - target); return distance <= 5 ? 4 : distance <= 12 ? 3 : distance <= 20 ? 2 : 0; };
const getPack = (id: string) => PACKS.find((pack) => pack.id === id) ?? PACKS[0];
const randomSpectrum = (pack: Pack, usedIds: string[]) => { const eligible = pack.spectra.filter((item) => !usedIds.includes(item.id)); const choices = eligible.length ? eligible : pack.spectra; return choices[Math.floor(Math.random() * choices.length)]; };

function pointOnArc(value: number, radius = 156) { const angle = Math.PI - (Math.PI * value) / 100; return { x: 200 + radius * Math.cos(angle), y: 190 - radius * Math.sin(angle) }; }
function Dial({ needle, target, revealed, onChange, onCommit, markers = [] }: { needle: number; target: number; revealed: boolean; onChange?: (value: number) => void; onCommit?: (value: number) => void; markers?: DialMarker[]; }) {
  const needlePoint = pointOnArc(needle, 150), targetStart = pointOnArc(clamp(target - 20)), targetEnd = pointOnArc(clamp(target + 20)), midStart = pointOnArc(clamp(target - 12)), midEnd = pointOnArc(clamp(target + 12)), centerStart = pointOnArc(clamp(target - 5)), centerEnd = pointOnArc(clamp(target + 5));
  return <div className="dial-wrap"><svg className="dial" viewBox="0 0 400 210" role="img" aria-label="Wavelength dial"><path className="dial-base" d="M44 190 A156 156 0 0 1 356 190" />{revealed && <><path className="dial-band outer" d={"M " + targetStart.x + " " + targetStart.y + " A156 156 0 0 1 " + targetEnd.x + " " + targetEnd.y} /><path className="dial-band middle" d={"M " + midStart.x + " " + midStart.y + " A156 156 0 0 1 " + midEnd.x + " " + midEnd.y} /><path className="dial-band center" d={"M " + centerStart.x + " " + centerStart.y + " A156 156 0 0 1 " + centerEnd.x + " " + centerEnd.y} /></>}{markers.map((marker) => { const point = pointOnArc(marker.value, 130); return <g className="dial-marker" key={marker.id}><title>{marker.label + ": " + Math.round(marker.value)}</title><circle cx={point.x} cy={point.y} r="6" /><text x={point.x} y={point.y - 11} textAnchor="middle">{marker.label.slice(0, 10)}</text></g>; })}<line className="dial-needle" x1="200" y1="190" x2={needlePoint.x} y2={needlePoint.y} /><circle className="dial-hub" cx="200" cy="190" r="10" /><text x="30" y="207">0</text><text x="355" y="207">100</text></svg>{onChange && <input aria-label="Tune the Wavelength dial" className="dial-slider" type="range" min="0" max="100" value={needle} onChange={(event) => onChange(clamp(Number(event.target.value)))} onPointerUp={() => onCommit?.(needle)} onKeyUp={() => onCommit?.(needle)} />}</div>;
}
function GameSetup({ selectedPackId, totalRounds, onPackChange, onRoundsChange, onStart, startLabel, disabled = false }: { selectedPackId: string; totalRounds: number; onPackChange: (packId: string) => void; onRoundsChange: (rounds: number) => void; onStart: () => void; startLabel: string; disabled?: boolean; }) {
  const pack = getPack(selectedPackId), maximum = Math.min(20, pack.spectra.length);
  return <section className="game-setup" aria-label="Wavelength game setup"><label>Prompt pack<select value={selectedPackId} onChange={(event) => onPackChange(event.target.value)} disabled={disabled}>{PACKS.map((item) => <option key={item.id} value={item.id}>{item.emoji} {item.name}</option>)}</select></label>{pack.id === "naughty" && <p className="pack-note">Adults only · flirty prompts for consenting adults.</p>}<label>Number of rounds<select value={Math.min(totalRounds, maximum)} onChange={(event) => onRoundsChange(Number(event.target.value))} disabled={disabled}>{Array.from({ length: maximum }, (_, index) => index + 1).map((round) => <option key={round} value={round}>{round}</option>)}</select></label><p>{pack.spectra.length} tagged questions available in {pack.name}.</p><button onClick={onStart} disabled={disabled}>{startLabel}</button></section>;
}

export default function Home() {
  const [phase, setPhase] = useState<Phase>("library"), [name, setName] = useState(""), [liveRoom, setLiveRoom] = useState<RoomSnapshot | null>(null), [liveRole, setLiveRole] = useState<CurrentRoomPlayer | null>(null), [roomPlayers, setRoomPlayers] = useState<RoomPlayer[]>([]);
  const [selectedPackId, setSelectedPackId] = useState(PACKS[0].id), [selectedRoundCount, setSelectedRoundCount] = useState(5), [localPackId, setLocalPackId] = useState(PACKS[0].id), [localRoundCount, setLocalRoundCount] = useState(5), [localRound, setLocalRound] = useState(0), [usedLocalContent, setUsedLocalContent] = useState<string[]>([]);
  const [spectrum, setSpectrum] = useState<Spectrum>(PACKS[0].spectra[0]), [target, setTarget] = useState(50), [needle, setNeedle] = useState(50), [clue, setClue] = useState(""), [groupScore, setGroupScore] = useState(0), [localDeadline, setLocalDeadline] = useState<string | null>(null), [localTimedOutPhase, setLocalTimedOutPhase] = useState<"clue" | "tune" | null>(null), [liveTarget, setLiveTarget] = useState<number | null>(null), [liveRoundId, setLiveRoundId] = useState<string | null>(null), [livePreviews, setLivePreviews] = useState<Record<string, WavelengthPreview>>({}), [notice, setNotice] = useState("Choose a game, then invite your people.");
  const previewPublisher = useRef<ReturnType<typeof createWavelengthPreviewPublisher> | null>(null), previewSequence = useRef(0), lastPreviewSentAt = useRef(0);
  const liveRoomId = liveRoom?.id, liveState = (liveRoom?.game_state ?? {}) as Record<string, unknown>;
  const currentPhase = (liveRoom ? (liveState.phase === "lobby" ? "game" : liveState.phase || "game") : phase) as Phase;
  const currentSpectrum = (liveRoom && liveState.spectrum ? liveState.spectrum : spectrum) as Spectrum, currentTarget = typeof liveState.target === "number" ? liveState.target : liveTarget ?? target, currentNeedle = liveRoom ? (typeof liveState.needle === "number" ? liveState.needle : null) : needle, currentScore = liveRoom ? liveRoom.group_score : groupScore;
  const isLiveKeeper = Boolean(liveRole && liveState.keeperId === liveRole.userId), isLiveHost = Boolean(liveRole && liveRoom?.host_id === liveRole.userId), roundNumber = liveRoom ? Number(liveState.currentRound ?? 0) : localRound, roundTotal = liveRoom ? Number(liveState.totalRounds ?? selectedRoundCount) : localRoundCount;
  const revealScore = useMemo(() => scoreGuess(needle, target), [needle, target]);

  useEffect(() => { if (!liveRoomId) return; void getCurrentRoomPlayer(liveRoomId).then(setLiveRole).catch((error: Error) => setNotice(error.message)); void listRoomPlayers(liveRoomId).then(setRoomPlayers).catch((error: Error) => setNotice(error.message)); }, [liveRoomId]);
  useEffect(() => { if (!liveRoomId) return; return subscribeToRoom(liveRoomId, setLiveRoom); }, [liveRoomId]);
  useEffect(() => { if (!liveRoomId) return; return subscribeToRoomPlayers(liveRoomId, setRoomPlayers); }, [liveRoomId]);
  useEffect(() => { if (!liveRoomId || !isLiveKeeper || !["clue", "tune"].includes(currentPhase)) return; void getCurrentWavelengthRound(liveRoomId).then((round) => { setLiveTarget(round?.target ?? null); setLiveRoundId(round?.id ?? null); }).catch((error: Error) => setNotice(error.message)); }, [currentPhase, isLiveKeeper, liveRoomId, liveState.roundId]);
  useEffect(() => { const roundId = typeof liveState.roundId === "string" ? liveState.roundId : null; if (!liveRoomId || !liveRole || isLiveKeeper || currentPhase !== "tune" || !roundId) { previewPublisher.current?.dispose(); previewPublisher.current = null; return; } const publisher = createWavelengthPreviewPublisher(liveRoomId, roundId, liveRole.userId); previewPublisher.current = publisher; return () => { publisher.dispose(); if (previewPublisher.current === publisher) previewPublisher.current = null; }; }, [currentPhase, isLiveKeeper, liveRole, liveRoomId, liveState.roundId]);
  useEffect(() => { const roundId = typeof liveState.roundId === "string" ? liveState.roundId : liveRoundId; if (!liveRoomId || !liveRole || currentPhase !== "tune" || !roundId) return; const playerIds = roomPlayers.filter((player) => player.userId !== liveRole.userId).map((player) => player.userId); const clear = window.setTimeout(() => setLivePreviews({}), 0); const unsubscribe = subscribeToWavelengthPreviews(liveRoomId, roundId, playerIds, (preview) => setLivePreviews((previous) => { const known = previous[preview.playerId]; return known && known.sequence > preview.sequence ? previous : { ...previous, [preview.playerId]: preview }; })); return () => { window.clearTimeout(clear); unsubscribe(); }; }, [currentPhase, liveRole, liveRoomId, liveRoundId, liveState.roundId, roomPlayers]);
  useEffect(() => { if (currentPhase !== "tune") return; const interval = window.setInterval(() => { const cutoff = Date.now() - 3000; setLivePreviews((previous) => Object.fromEntries(Object.entries(previous).filter(([, preview]) => preview.receivedAt >= cutoff))); }, 1000); return () => window.clearInterval(interval); }, [currentPhase]);

  const startLocalRound = (nextRound: number, usedIds: string[], packId = localPackId) => { const nextSpectrum = randomSpectrum(getPack(packId), usedIds); setSpectrum(nextSpectrum); setTarget(randomTarget()); setNeedle(50); setClue(""); setLocalRound(nextRound); setUsedLocalContent([...usedIds, nextSpectrum.id]); setLocalTimedOutPhase(null); setLocalDeadline(new Date(Date.now() + 60_000).toISOString()); setPhase("clue"); };
  const beginLocalGame = () => { if (!name.trim()) return setNotice("Add a display name first."); setGroupScore(0); setLocalPackId(selectedPackId); setLocalRoundCount(selectedRoundCount); setUsedLocalContent([]); startLocalRound(1, [], selectedPackId); setNotice(name.trim() + " is the Keeper. The target is private on this device."); };
  const beginLiveGame = () => { if (liveRoom) void wavelengthStartGame(liveRoom.id, selectedPackId, selectedRoundCount).catch((error: Error) => setNotice(error.message)); };
  const startLiveRound = () => { if (liveRoom) void wavelengthStartRound(liveRoom.id).catch((error: Error) => setNotice(error.message)); };
  const revealLocal = () => { setLocalDeadline(null); setGroupScore((score) => score + revealScore); setPhase(localRound >= localRoundCount ? "complete" : "reveal"); };
  const copyRoomCode = async () => { if (!liveRoom) return; try { await navigator.clipboard.writeText(liveRoom.code); setNotice("Room code copied. Send it to your friends."); } catch { setNotice("Share room code " + liveRoom.code + "."); } };
  const handleTimeout = useCallback(() => { if (liveRoom) { void wavelengthTimeoutPhase(liveRoom.id).catch((error: Error) => setNotice(error.message)); return; } setLocalDeadline(null); setLocalTimedOutPhase(currentPhase === "tune" ? "tune" : "clue"); setPhase(localRound >= localRoundCount ? "complete" : "timeout"); }, [currentPhase, liveRoom, localRound, localRoundCount]);
  const publishPreview = (position: number, force = false) => { const now = Date.now(); if (!force && now - lastPreviewSentAt.current < 200) return; const publisher = previewPublisher.current; if (!publisher) return; lastPreviewSentAt.current = now; previewSequence.current += 1; void publisher.send(position, previewSequence.current).catch((error: Error) => setNotice(error.message)); };
  const updateNeedle = (value: number) => { setNeedle(value); publishPreview(value); };
  const deadlineAt = liveRoom ? (typeof liveState.deadlineAt === "string" ? liveState.deadlineAt : null) : localDeadline, timedOut = Boolean(liveState.timedOut) || Boolean(localTimedOutPhase), timedOutPhase = localTimedOutPhase ?? (liveState.timedOutPhase === "tune" ? "tune" : "clue");
  const spectrumVisible = !liveRoom || isLiveKeeper || currentPhase !== "clue", previewMarkers = Object.values(livePreviews).map((preview) => ({ id: preview.playerId, label: roomPlayers.find((player) => player.userId === preview.playerId)?.displayName ?? "Player", value: preview.position }));

  if (currentPhase === "library") return <main className="library-shell"><header><Link className="brand" href="/">Game Library</Link><span>Simple games for your people.</span></header><section className="library-hero"><p className="eyebrow">PLAY TOGETHER</p><h1>Choose your game.</h1><p className="lede">Every game gets its own card. Pick one to see how you want to play.</p><div className="game-grid"><article className="game-card"><div><p className="eyebrow">READY TO PLAY</p><h2>Wavelength</h2><p>Give one clue. Find the hidden spot. Get on the same wavelength.</p><span className="game-meta">2–8 players · 15 minutes</span></div><button onClick={() => setPhase("game")}>Open Wavelength</button></article><article className="game-card coming-soon"><div><p className="eyebrow">UP NEXT</p><h2>Pulse Vote</h2><p>Make a private prediction, then see where the room lands.</p><span className="game-meta">3–8 players · coming soon</span></div><button disabled>Coming soon</button></article></div></section></main>;
  if (currentPhase === "game") return <main className="game-shell"><header><button className="back-button" onClick={() => { setLiveRoom(null); setLiveRole(null); setPhase("library"); }}>← Home</button><span className="game-title">Wavelength</span><span className="score">2–8 players</span></header><section className="game-choice"><p className="eyebrow">WAVELENGTH</p>{liveRoom ? <><h1>Your room is ready.</h1><p>Share the code, then have the host choose a prompt pack and number of rounds.</p><div className="room-ready"><div><span className="eyebrow">ROOM CODE</span><strong>{liveRoom.code}</strong></div><button className="copy-button" onClick={() => void copyRoomCode()}>Copy code</button><div className="room-roster" aria-live="polite"><div className="eyebrow">PLAYERS IN ROOM</div><ul>{roomPlayers.map((player) => <li key={player.userId}><span>{player.displayName}</span>{player.userId === liveRoom.host_id && <span className="roster-role">HOST</span>}</li>)}</ul><small>{roomPlayers.length} {roomPlayers.length === 1 ? "player" : "players"} joined</small></div>{isLiveHost ? <GameSetup selectedPackId={selectedPackId} totalRounds={selectedRoundCount} onPackChange={setSelectedPackId} onRoundsChange={setSelectedRoundCount} onStart={beginLiveGame} startLabel="Start Wavelength" /> : <p>{liveRole ? "Waiting for the host to choose the pack and begin." : "Confirming your room…"}</p>}</div></> : <><h1>How do you want to play?</h1><p>Pass one device around, or make a private room and bring friends in remotely.</p><label className="name-field">Display name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Jordan" maxLength={24} /></label><div className="play-options"><article><h2>In the room</h2><p>Take turns as Keeper and play for a shared score.</p><GameSetup selectedPackId={selectedPackId} totalRounds={selectedRoundCount} onPackChange={setSelectedPackId} onRoundsChange={setSelectedRoundCount} onStart={beginLocalGame} startLabel="Start local game" /></article><article><h2>Online</h2><p>Create a private room or join one with a code.</p><MultiplayerLobby displayName={name} gameSlug="signal-spectrum" onRoomChange={setLiveRoom} onRoleChange={setLiveRole} /></article></div></>}<small className="notice">{notice}</small></section></main>;
  const nextRound = () => { if (liveRoom) startLiveRound(); else startLocalRound(localRound + 1, usedLocalContent); }, canAdvanceLive = !liveRoom || isLiveHost;
  return <main className="game-shell"><header><button className="back-button" onClick={() => { setLiveRoom(null); setLiveRole(null); setPhase("library"); }}>← Home</button><span className="game-title">Wavelength</span><span className="score">Group score {currentScore}</span></header><section className="game-board"><div className="round-badge">Round {roundNumber}/{roundTotal}</div>{spectrumVisible ? <div className="spectrum"><span>{currentSpectrum.left}</span><div /><span>{currentSpectrum.right}</span></div> : <div className="spectrum spectrum-hidden"><span aria-hidden="true">?</span><div /><span aria-hidden="true">?</span></div>}
    {currentPhase === "clue" && (liveRoom && !isLiveKeeper ? <div className="panel"><p className="eyebrow">KEEPER’S TURN</p><Countdown deadlineAt={deadlineAt} onExpired={handleTimeout} /><h1>Listen closely.</h1><p>The Keeper is choosing a clue. The target stays private until the reveal.</p></div> : <div className="panel"><p className="eyebrow">KEEPER ONLY</p><Countdown deadlineAt={deadlineAt} onExpired={handleTimeout} />{liveRoom && liveTarget === null ? <p>Setting the hidden target…</p> : <><Dial needle={currentTarget} target={currentTarget} revealed /><p>Think of one clue, share it, then let the group tune the dial.</p><form onSubmit={(event) => { event.preventDefault(); if (!clue.trim()) return; if (liveRoom) void wavelengthSubmitClue(liveRoom.id, clue).catch((error: Error) => setNotice(error.message)); else { setLocalDeadline(new Date(Date.now() + 90_000).toISOString()); setPhase("tune"); } }}><input value={clue} onChange={(event) => setClue(event.target.value)} placeholder="Your clue" maxLength={60} /><button>Share clue</button></form></>}</div>)}
    {currentPhase === "tune" && <div className="panel"><p className="clue">“{String(liveState.clue ?? clue)}”</p><Countdown deadlineAt={deadlineAt} onExpired={handleTimeout} />{liveRoom && isLiveKeeper ? <><p>The group is discussing and setting the dial. Their live guesses appear below.</p><Dial needle={currentTarget} target={currentTarget} revealed markers={previewMarkers} /><p className="preview-status">{previewMarkers.length ? previewMarkers.length + " player" + (previewMarkers.length === 1 ? "" : "s") + " adjusting" : "Waiting for player adjustments…"}</p></> : <><p>Talk it through, then lock the group’s dial position.</p><Dial needle={needle} target={currentTarget} revealed={false} markers={previewMarkers} onChange={updateNeedle} onCommit={(value) => publishPreview(value, true)} /><button onClick={() => { if (liveRoom) void wavelengthSubmitTune(liveRoom.id, needle).catch((error: Error) => setNotice(error.message)); else { setLocalDeadline(null); setPhase("reveal_pending"); } }}>Lock in</button></>}</div>}
    {currentPhase === "reveal_pending" && <div className="panel"><p className="eyebrow">DIAL LOCKED</p><h1>Ready for the reveal?</h1><p>{liveRoom && !isLiveKeeper ? "The Keeper is revealing the shared score." : "The Keeper can reveal the shared score now."}</p>{(!liveRoom || isLiveKeeper) && <button onClick={() => { if (liveRoom) void wavelengthRevealRound(liveRoom.id).catch((error: Error) => setNotice(error.message)); else revealLocal(); }}>Reveal score</button>}</div>}
    {(currentPhase === "reveal" || currentPhase === "timeout") && <div className="panel">{typeof currentNeedle === "number" ? <Dial needle={currentNeedle} target={currentTarget} revealed /> : <p className="eyebrow">NO DIAL LOCKED</p>}<h1>{currentPhase === "timeout" ? (timedOutPhase === "tune" ? "The group ran out of time." : "The Keeper ran out of time.") : timedOut ? "Time’s up · 0 points" : liveRoom ? Number(liveState.points ?? 0) + " points" : revealScore ? revealScore + " points" : "Just outside"}</h1><p>Group score: {currentScore}</p>{canAdvanceLive && <button onClick={nextRound}>Next round</button>}</div>}
    {currentPhase === "complete" && <div className="panel"><p className="eyebrow">WAVELENGTH</p>{typeof currentNeedle === "number" && <Dial needle={currentNeedle} target={currentTarget} revealed />}<h1>{timedOut ? "Time’s up" : "Game complete"}</h1><p>Final group score: {currentScore}</p>{liveRoom ? isLiveHost ? <GameSetup selectedPackId={selectedPackId} totalRounds={selectedRoundCount} onPackChange={setSelectedPackId} onRoundsChange={setSelectedRoundCount} onStart={beginLiveGame} startLabel="Play another game" /> : <p>Waiting for the host to choose the next pack.</p> : <GameSetup selectedPackId={selectedPackId} totalRounds={selectedRoundCount} onPackChange={setSelectedPackId} onRoundsChange={setSelectedRoundCount} onStart={beginLocalGame} startLabel="Play another game" />}</div>}
  </section><small className="notice">{notice}</small></main>;
}
