-- Signal Party: anonymous, room-code multiplayer data model.
-- Enable Anonymous Sign-Ins in Auth before applying.
create extension if not exists pgcrypto;
create table public.rooms(id uuid primary key default gen_random_uuid(),code text unique not null check(code~'^[A-Z0-9]{6}$'),host_id uuid not null references auth.users(id) on delete cascade,status text not null default 'lobby' check(status in('lobby','clue','tune','intercept','reveal','complete')),active_team text not null default 'amber' check(active_team in('amber','violet')),amber_score integer not null default 0 check(amber_score>=0),violet_score integer not null default 0 check(violet_score>=0),created_at timestamptz not null default now());
create table public.room_players(room_id uuid not null references public.rooms(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null check(char_length(display_name) between 1 and 24),team text not null check(team in('amber','violet')),is_keeper boolean not null default false,joined_at timestamptz not null default now(),primary key(room_id,user_id));
create table public.rounds(id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id) on delete cascade,keeper_id uuid not null references auth.users(id),spectrum jsonb not null,target integer not null check(target between 0 and 100),clue text check(char_length(clue)<=60),needle integer check(needle between 0 and 100),intercept text check(intercept in('left','right')),active_score integer not null default 0,intercept_score integer not null default 0,created_at timestamptz not null default now());
alter table public.rooms enable row level security;alter table public.room_players enable row level security;alter table public.rounds enable row level security;
create policy "players read room" on public.rooms for select to authenticated using(exists(select 1 from public.room_players p where p.room_id=id and p.user_id=(select auth.uid())));
create policy "players read roster" on public.room_players for select to authenticated using(exists(select 1 from public.room_players mine where mine.room_id=room_id and mine.user_id=(select auth.uid())));
create policy "keeper or revealed round" on public.rounds for select to authenticated using(exists(select 1 from public.room_players p join public.rooms r on r.id=p.room_id where p.room_id=rounds.room_id and p.user_id=(select auth.uid()) and(r.status='reveal' or rounds.keeper_id=(select auth.uid()))));
alter publication supabase_realtime add table public.rooms,public.room_players,public.rounds;
-- Mutations belong in server-side route handlers; never expose a service_role key in browser code.
